### ISSUE TITLE
[Desktop Bug] Can't figure out how to see background

### ISSUE THREAD

**Issue by borenstein** [ArtexJay/Obsidian-CyberGlow#56]
**Describe the bug**
I installed the theme and set it to the current theme, and I installed+enabled the recommended plugin (Style Settings), but the background is still plain black.

**To Reproduce**
1. Create a brand new repo
2. Install + switch to the theme
3. Install + enable Style Settings
4. Restart Obsidian

**Expected behavior**
At some point in the above sequence, I expected to see the background shown in the theme gallery.

**Screenshots, Gifs, Video**
<img width="944" alt="Screenshot 2023-06-03 at 7 54 23 PM" src="https://github.com/ArtexJay/Obsidian-CyberGlow/assets/4448415/4502675b-fe6e-44d1-8256-1f9ce7ca599d">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Obsidian Version: 1.3.5
 - CyberGlow Version: 7.9.0

**Additional context**
This theme reminds me of some beloved games from my childhood! Wonderful.

**Comment by ArtexJay** [comment]
Once you enable Style Settings you need go to Style Settings Page, there you will see all the controls for setting the custom background, changing opacity, and much more.

If you don't have Style Settings as a keyboard shortcut you can find the page by opening Settings (gear icon) in Obsidian, then scroll on the left side pane down to community plugins. Under community plugins o you should see the Style Settings plug in, click that and you will see all the Style Settings you're looking for. There should be a toggle there to Enable background wallpaper.

![image](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/32932497/ce9c1d70-59fe-4168-990f-c60b46bd4ccc)

**Comment by borenstein** [comment]
Thanks so much for your quick response! I did do that, but I don't see the background shown in the theme preview even after doing so. Apologies for not saying so earlier. See the screenshot below. Is the background in the preview just not part of the theme itself?

<img width="1182" alt="Screenshot 2023-06-03 at 8 44 50 PM" src="https://github.com/ArtexJay/Obsidian-CyberGlow/assets/4448415/4bd30bd4-b513-464e-ada7-442c732d61f4">

**Comment by ArtexJay** [comment]
Make sure to check to check the Opacity slider, you may need to move the slider a bit.

It's included in theme, as in, there is a link that points to the image. If it's not working switch to custom, and input this url("https://media.discordapp.net/attachments/931552763467411487/1072059542336176218/Obsidian-Community.png") in the Custom Workspace Background Image.

Local URL Link don't work anymore just fyi, not due to the theme.

**Comment by ArtexJay** [comment]
Wait are you talking about this preview image? 
![image](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/32932497/ed51368c-f44d-42e8-983a-8f5f59690e29)

This background isn't included, I can provide you a link to it online though.

**Comment by borenstein** [comment]
Yes, and that would be lovely!

**Comment by ArtexJay** [comment]
I got the image from deviantart and used it as my personal desktop wallpaper for a bit and thought it would look amazing on Obsidian for my theme. The artist makes really beautiful art on DeviantArt. This one was an humanized Moltres from Pokemon flying in the sky.
https://www.deviantart.com/sakimichan/art/Go-623780055

Otherwise the background effect does work for you right? You just wanted to have the same background from the preview then?

**Comment by borenstein** [comment]
Thank you! Yup, that's all I needed!
